### PR TITLE
Minor bug fix, readme.md updated and requirements.txt added

### PR DESCRIPTION
**Pull request by mananpal1997**

### CODE REVIEW

**Comment by mbad0la** [comment]
@amaneureka @da230896, Ayush please review this PR asap.

**Comment by ayushgarg1804** [comment]
Looks good. Can you merge all of them into one commit?

**Comment by mbad0la** [comment]
@mananpal1997 look at this [article](http://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git) to know more about merging/squashing your commits into one.

**Comment by mananpal1997** [comment]
@ayushgarg1804 why all of them into one? not an issue, just asking
@mbad0la done sir.

**Comment by ayushgarg1804** [comment]
@mananpal1997 It's best to keep all minor changes ( some of which are just 1-2 lines per commit) into one major commit to make history less noisy. Just thats why, its always a good practice for a PR.

**Comment by mananpal1997** [comment]
@ayushgarg1804 is it okay now?

**Comment by ayushgarg1804** [comment]
@mananpal1997 No, not this you just increased the number of commits while you had merge all of them into one commit! Basically refer to the link provided by @mbad0la and to make sure you executed it correctly make sure the amount of commits (on commits tab) on PR is one. I guess you only made changes for your forked repo in commit rebase.

**Comment by ayushgarg1804** [comment]
Anyway i'll do it for now

**Pull request merged**
