### PR TITLE
Keys support

### PR DESCRIPTION
**Pull request by ayushgarg1804**
Keys support works for the current word only and not for previous words

### CODE REVIEW

**Comment by amaneureka** [comment]
Can you also include "Delete" Key?

**Comment by mbad0la** [comment]
@amaneureka I hope you'll handle the PR as you are maintaining the repo.

**Comment by amaneureka** [comment]
Cool, working fine.
could you also add Home button feature and squash all of them in one changeset? @ayushgarg1804

**Comment by ayushgarg1804** [comment]
No need of adding Home button feature as buffer will get empty anyway.

**Pull request merged**
