### PR TITLE
Code clean up and files nicely put in directory

### PR DESCRIPTION
**Pull request by prabhakar267**
mentions : @mbad0la

### CODE REVIEW

**Comment by amaneureka** [comment]
I think it is always a good strategy that a repo maintainer approves pull request before merging?

@ayushgarg1804

**Comment by mbad0la** [comment]
@amaneureka I agree but I guess this wasn't a breaking change, just a mere organisation of resources in this repository. It isn't harmful for the repository. What say?

**Comment by amaneureka** [comment]
@mbad0la Yeah I agree; no issue with this pull request. It was just a humble request :)

**Comment by mbad0la** [comment]
@amaneureka it's a valid request. We'll add branch protection on all repositories along with PR reviews, even for the admins in a month or two.

**Comment by prabhakar267** [comment]
@amaneureka I know, that's why I had a word with @mbad0la before merging the changing and as he said since these were not major / breaking changes, that's why I didn't feel the need to wait for an approval
But I agree this shouldn't be done. My bad. Won't repeat and would request everyone to follow the same. :smile:

**Pull request merged**
